(function () {
    'use strict';

    const root = window;
    const GUI = root.SynticoreGui || {};
    const DEFAULT_LOG_LEVEL_VISIBILITY = {
        log: true,
        info: true,
        notice: true,
        warn: true,
        error: true,
        fatal: true,
        success: true,
        begin: true,
        end: true,
        init: true,
        shutdown: true,
        trace: true,
        detail: true,
        debug: true
    };

    GUI.STATE = {
        bootstrap: null,
        activeTopTab: 'task',
        selectedProject: '',
        configMode: 'project',
        configModel: null,
        configData: {},
        configSectionState: {},
        configUnionBranchMemory: {},
        configCustomDraft: null,
        configSectionStateSavePromise: null,
        configDirty: false,
        configWatchTimer: null,
        configWatchIntervalMs: 3000,
        configWatchSignature: '',
        configWatchWarnedSignature: '',
        wikiPath: '/wiki',
        wikiPage: null,
        theme: 'dark',
        showButtonTitles: false,
        logEntries: [],
        logOptionsExpanded: false,
        logLevelVisibility: Object.assign({}, DEFAULT_LOG_LEVEL_VISIBILITY),
        logSearchQuery: '',
        logStickToBottom: true,
        logScrollTop: 0,
        logPreferenceSaveTimer: null,
        authRequired: false,
        activeTooltipTarget: null,
        tooltipLongPressTimer: null,
        tooltipLongPressTarget: null,
        tooltipSuppressClick: false,
        tooltipSuppressClickTarget: null,
        tooltipDismissUntil: 0,
        tooltipOpenSource: '',
        tooltipFocusRepositionFrame: null,
        tooltipKeyboardNavUntil: 0,
        tooltipPointerX: null,
        tooltipPointerY: null,
        tooltipPointerInside: false,
        clientLogContext: null,
        clientLogContextPromise: null,
        devSecretStage: 0,
        devSecretDeadline: 0,
        devSecretHoldTimer: null,
        devSecretPointerId: null,
        devSecretPointerStartX: null,
        devSecretPointerStartY: null
    };

    GUI.UI = {
        loadingOverlay: document.getElementById('loading-overlay'),
        loadingText: document.getElementById('loading-text'),
        authOverlay: document.getElementById('auth-overlay'),
        authText: document.getElementById('auth-text'),
        authToken: document.getElementById('auth-token'),
        authError: document.getElementById('auth-error'),
        authSubmit: document.getElementById('auth-submit'),
        tooltipLayer: document.getElementById('tooltip-layer'),
        browseDirectoryButtons: Array.from(document.querySelectorAll('[data-browse-directory]')),
        modals: Array.from(document.querySelectorAll('[data-modal]')),
        dropdowns: Array.from(document.querySelectorAll('[data-dropdown]')),
        settingsMenu: document.querySelector('.settings-menu'),
        settingsMenuToggle: document.querySelector('.settings-menu [data-dropdown-toggle]'),
        brandLogo: document.querySelector('.topbar .brand__logo'),
        themeToggle: document.getElementById('theme-toggle'),
        themeToggleLabel: document.getElementById('theme-toggle-label'),
        buttonTitlesToggle: document.getElementById('button-titles-toggle'),
        buttonTitlesToggleLabel: document.getElementById('button-titles-toggle-label'),
        networkPublicToggle: document.getElementById('network-public-toggle'),
        networkTrustedToggle: document.getElementById('network-trusted-toggle'),
        networkToken: document.getElementById('network-token'),
        networkTokenRegenerate: document.getElementById('network-token-regenerate'),
        networkLocalUrl: document.getElementById('network-local-url'),
        networkLanUrl: document.getElementById('network-lan-url'),
        networkNote: document.getElementById('network-note'),
        copyTriggers: Array.from(document.querySelectorAll('[data-copy-trigger]')),
        projectPathControl: document.querySelector('.project-path-control'),
        projectPath: document.getElementById('project-path'),
        projectPathToggle: document.getElementById('project-path-toggle'),
        projectPathSuggestions: document.getElementById('project-path-suggestions'),
        projectPathSuggestionsList: document.getElementById('project-path-suggestions-list'),
        projectPathField: document.querySelector('.project-path-field'),
        projectBrowse: document.getElementById('project-browse'),
        projectOpen: document.getElementById('project-open'),
        terminalRoot: document.getElementById('terminal-root'),
        versionBadge: document.getElementById('version-badge'),
        versionText: document.getElementById('version-text'),
        versionState: document.getElementById('version-state'),
        versionDetail: document.getElementById('version-detail'),
        taskColumns: document.getElementById('task-columns'),
        configPath: document.getElementById('config-path'),
        configMtime: document.getElementById('config-mtime'),
        configIntroCopy: document.querySelector('.config-intro .panel-intro'),
        configForm: document.getElementById('config-form'),
        configRaw: document.getElementById('config-raw'),
        configSchemaRaw: document.getElementById('config-schema-raw'),
        configEditorShell: document.querySelector('.config-editor-shell'),
        configEditor: document.getElementById('config-editor'),
        configEditorHighlight: document.getElementById('config-editor-highlight'),
        configEditorHighlightCode: document.getElementById('config-editor-highlight-code'),
        configSchemaEditorShell: document.querySelector('#config-schema-raw .config-editor-shell'),
        configSchemaEditor: document.getElementById('config-schema-editor'),
        configSchemaEditorHighlight: document.getElementById('config-schema-editor-highlight'),
        configSchemaEditorHighlightCode: document.getElementById('config-schema-editor-highlight-code'),
        configReload: document.getElementById('config-reload'),
        configSave: document.getElementById('config-save'),
        wikiBreadcrumbs: document.getElementById('wiki-breadcrumbs'),
        wikiToc: document.getElementById('wiki-toc'),
        wikiContent: document.getElementById('wiki-content'),
        logEntries: document.getElementById('log-entries'),
        logEmpty: document.getElementById('log-empty'),
        logOptionsPanel: document.getElementById('log-options-panel'),
        logOptionsBody: document.getElementById('log-options-body'),
        logOptionsToggle: document.getElementById('log-options-toggle'),
        logSearch: document.getElementById('log-search'),
        logCopy: document.getElementById('log-copy'),
        logClear: document.getElementById('log-clear'),
        logFilterGroupButtons: Array.from(document.querySelectorAll('[data-log-filter-group]')),
        logFilterButtons: Array.from(document.querySelectorAll('[data-log-filter]')),
        configModeTabs: Array.from(document.querySelectorAll('[data-mode]')),
        topTabs: Array.from(document.querySelectorAll('.tabs:not(.tabs--sub) .tab[data-tab]')),
        topPanels: {
            task: document.getElementById('tab-task'),
            config: document.getElementById('tab-config'),
            wiki: document.getElementById('tab-wiki'),
            log: document.getElementById('tab-log')
        },
        newProjectToggle: document.getElementById('new-project-toggle'),
        newProjectModal: document.getElementById('new-project-modal'),
        newProjectClose: document.getElementById('new-project-close'),
        licenseSoftwareToggle: document.getElementById('license-software-toggle'),
        licenseSoftwareModal: document.getElementById('license-software-modal'),
        licenseSoftwareClose: document.getElementById('license-software-close'),
        newProjectDir: document.getElementById('new-project-dir'),
        newProjectTemplateCards: document.getElementById('new-project-template-cards'),
        newProjectTemplate: document.getElementById('new-project-template'),
        newProjectForce: document.getElementById('new-project-force'),
        newProjectCreate: document.getElementById('new-project-create'),
        devModal: document.getElementById('dev-modal'),
        devModalClose: document.getElementById('dev-modal-close'),
        devOpenTaskSurface: document.getElementById('dev-open-task-surface'),
        devOpenProjectConfigSurface: document.getElementById('dev-open-project-config-surface'),
        devOpenLogConfigSurface: document.getElementById('dev-open-log-config-surface'),
        devOpenLogSurface: document.getElementById('dev-open-log-surface'),
        devOpenNewProjectSurface: document.getElementById('dev-open-new-project-surface'),
        devReloadWikiSurface: document.getElementById('dev-reload-wiki-surface'),
        devArchiveRecents: document.getElementById('dev-archive-recents'),
        devRestoreRecents: document.getElementById('dev-restore-recents'),
        devLogSuite: document.getElementById('dev-log-suite'),
        devLogClear: document.getElementById('dev-log-clear')
    };

    GUI.DEFAULT_LOG_LEVEL_VISIBILITY = DEFAULT_LOG_LEVEL_VISIBILITY;

    root.SynticoreGui = GUI;
})();
